"""change case text columns to unicode

Revision ID: 7391ae438a78
Revises: 792048c467d9
Create Date: 2026-08-17 20:15:46.479737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7391ae438a78'
down_revision = '792048c467d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Cases', schema=None) as batch_op:
        batch_op.alter_column('ApplicantName',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=255),
               existing_nullable=True)
        batch_op.alter_column('AgencyName',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=255),
               existing_nullable=True)
        batch_op.alter_column('Status',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=50),
               existing_nullable=True)
        batch_op.alter_column('Priority',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=50),
               existing_nullable=True)
        batch_op.alter_column('CurrentStepName',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=255),
               existing_nullable=True)
        batch_op.alter_column('SourceType',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=50),
               existing_nullable=True)

    with op.batch_alter_table('Departments', schema=None) as batch_op:
        batch_op.alter_column('Name',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=255),
               existing_nullable=True)

    with op.batch_alter_table('ProcedureFields', schema=None) as batch_op:
        batch_op.alter_column('Name',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=255),
               existing_nullable=False)

    with op.batch_alter_table('Procedures', schema=None) as batch_op:
        batch_op.alter_column('Name',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=255),
               existing_nullable=False)

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('Username',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=100),
               existing_nullable=True)
        batch_op.alter_column('FullName',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('FullName',
               existing_type=sa.Unicode(length=255),
               type_=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('Username',
               existing_type=sa.Unicode(length=100),
               type_=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)

    with op.batch_alter_table('Procedures', schema=None) as batch_op:
        batch_op.alter_column('Name',
               existing_type=sa.Unicode(length=255),
               type_=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    with op.batch_alter_table('ProcedureFields', schema=None) as batch_op:
        batch_op.alter_column('Name',
               existing_type=sa.Unicode(length=255),
               type_=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    with op.batch_alter_table('Departments', schema=None) as batch_op:
        batch_op.alter_column('Name',
               existing_type=sa.Unicode(length=255),
               type_=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)

    with op.batch_alter_table('Cases', schema=None) as batch_op:
        batch_op.alter_column('SourceType',
               existing_type=sa.Unicode(length=50),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('CurrentStepName',
               existing_type=sa.Unicode(length=255),
               type_=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('Priority',
               existing_type=sa.Unicode(length=50),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('Status',
               existing_type=sa.Unicode(length=50),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('AgencyName',
               existing_type=sa.Unicode(length=255),
               type_=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('ApplicantName',
               existing_type=sa.Unicode(length=255),
               type_=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)

    # ### end Alembic commands ###
